import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react'

/**
 * A redux toolkit API slice that is used to fetch the Movie. The getMovieByName endpoint
 * is used by the Search Page. The getMovieById endpoint is used by the Movie Details component
 * and fetches the movie based on it's unique imdb ID.
 */
export const personApiSlice = createApi({
    reducerPath: 'personApi',
    baseQuery: fetchBaseQuery({ baseUrl: 'http://localhost:8080/api/people' }),
    endpoints: (builder) => ({

        getPeople: builder.query({
            query: () => `/`
        })
    }),
});

// Hooks are automatically generated by redux toolkit based on the endpoint names
export const { useGetPeopleQuery } = personApiSlice;